services:
  simulator:
    image: mars-iot-simulator:multiarch_v1
    restart: on-failure
    ports:
      - "8080:8080"

  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_LOGS: "error"

  ingestion-service:
    build: ./source/ingestion-service
    restart: on-failure
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: "rabbitmq"
      SIMULATOR_URL: "http://simulator:8080"
    depends_on:
      - rabbitmq
      - simulator

  frontend:
    build: ./source/frontend
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      PYTHONUNBUFFERED: 1
      RABBITMQ_HOST: "rabbitmq"
    depends_on:
      - rabbitmq